=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Gains)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Performance (Primary|Secondary)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Primary EMPTY>
<!ATTLIST Primary Skill CDATA #IMPLIED Stat CDATA #IMPLIED>
<!ELEMENT Secondary EMPTY>
<!ATTLIST Secondary Skill CDATA #IMPLIED Stat CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (#PCDATA)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED>
<!ELEMENT LoseTrait (#PCDATA)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Threshold CDATA #REQUIRED Action CDATA #REQUIRED Event CDATA #IMPLIED>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/Tailor.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Talr">
    <Description>
        She will make clothes and other items from fabrics.
    </Description>
    <Performance Modifier="work.tailor">
        <Primary Skill="Crafting"/>
        <Secondary Skill="Service" />
        <Secondary Skill="Magic" />
        <Secondary Stat="Intelligence" />
    </Performance>
    <Gains XP="5" Skill="3" />
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/BarMaid.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="BrMd">
    <Description>
        She will staff the bar and serve drinks.
    </Description>
    <Performance Modifier="work.barmaid">
        <Primary Skill="Service"/>
        <Primary Stat="Intelligence" />
        <Secondary Stat="Charisma" />
        <Secondary Skill="Performance" />
        <Secondary Skill="Brewing" />
    </Performance>
    <Gains XP="10" Skill="3">
        <LoseTrait Trait="Nervous" Threshold="40" Action="WORKBAR">
            ${name} seems to finally be getting over her shyness. She's not always so Nervous anymore.
        </LoseTrait>
        <GainTrait Trait="Charismatic" Threshold="60" Action="WORKBAR">
            Dealing with customers at the bar and talking with them about their problems has made ${name} more Charismatic.
        </GainTrait>
    </Gains>
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/MakePotions.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="MkPt">
    <Description>
        She will make various potions.
    </Description>
    <Performance Modifier="work.makepotions">
        <Primary Skill="Brewing"/>
        <Primary Skill="Herbalism"/>
        <Secondary Skill="Service" />
        <Secondary Skill="Magic" />
        <Secondary Skill="Cooking" />
    </Performance>
    <Gains XP="5" Skill="3" />
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/FilmBondage.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FBst">
    <Description>
        She will perform in a bondage scene.
    </Description>
    <Performance Modifier="work.film.bondage">
        <Primary Stat="Beauty"/>
        <Primary Stat="Charisma" />
        <Primary Stat="Dignity" />
    </Performance>
    <Gains XP="10" Skill="3">
        <GainTrait Trait="Porn Star" Threshold="80" Action="WORKMOVIE">
            She has performed in enough sex scenes that she has become a well known Porn Star.
        </GainTrait>
        <GainTrait Trait="Fake Orgasm Expert" Threshold="50" Action="SEX">
            She has become quite the Faker.
        </GainTrait>
        <GainTrait Trait="Slut" Threshold="80" Action="SEX" Event="2">
            ${name} has turned into quite a Slut.
        </GainTrait>
        <GainTrait Trait="Masochist" Threshold="65" Action="SEX">
            ${name} has turned into a Masochist from filming so many BDSM scenes.
        </GainTrait>
    </Gains>
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/Jeweler.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Jwlr">
    <Description>
        She will make jewelery.
    </Description>
    <Performance Modifier="work.jeweler">
        <Primary Skill="Crafting"/>
        <Secondary Skill="Magic" />
        <Secondary Stat="Confidence" />
        <Secondary Stat="Intelligence" />
        <Secondary Stat="Agility" />
    </Performance>
    <Gains XP="5" Skill="3">
    <GainTrait Trait="Sharp-Eyed" Threshold="50" Action="MAKEITEMS">
        Working on such small items has made ${name} rather Sharp-Eyed.
    </GainTrait>
    </Gains>
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/Janitor.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Jntr">
    <Description>
        She will clean the clinic.
    </Description>
    <Performance Modifier="work.cleaning">
        <Primary Skill="Service" />
        <Secondary Stat="Morality" />
        <Secondary Stat="Obedience" />
        <Secondary Stat="Agility" />
    </Performance>
    <Gains XP="0" Skill="0">
    </Gains>
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/Gardener.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Grdn">
    <Description>
        She will produce herbs.
    </Description>
    <Performance Modifier="work.gardener">
        <Primary Skill="Herbalism"/>
        <Secondary Skill="Farming" />
        <Secondary Stat="Constitution" />
        <Secondary Stat="Intelligence" />
    </Performance>
    <Gains XP="5" Skill="3" />
</Job>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Jobs/Nurse.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Nurs">
    <Description>
        Will help the doctor and heal sick people.
    </Description>
    <Performance Modifier="work.nurse">
        <Primary Skill="Medicine"/>
        <Secondary Stat="Intelligence" />
        <Secondary Stat="Charisma" />
    </Performance>
    <Gains XP="10" Skill="2">
        <GainTrait Trait="Charismatic" Threshold="60" Action="WORKNURSE">
            Dealing with patients and talking with them about their problems has made ${name} more Charismatic.
        </GainTrait>
        <LoseTrait Trait="Nervous" Threshold="30" Action="WORKNURSE">
            ${name} seems to finally be getting over her shyness. She's not always so Nervous anymore.
        </LoseTrait>
    </Gains>
</Job>
