=== DRSSX4756/crazys-wm-mod/Resources/Data/Treatments/treatment.dtd
<!ELEMENT Treatment (Description, Therapy?, Surgery?, Messages?)>
<!ATTLIST Treatment ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

<!ELEMENT Therapy (RemoveTrait*)>
<!ATTLIST Therapy Duration CDATA #REQUIRED FightChance CDATA #REQUIRED Title CDATA #REQUIRED Title CDATA #REQUIRED SuccessBonus CDATA #REQUIRED HealthDanger CDATA #REQUIRED>

<!ELEMENT Surgery (TraitExclude*)>
<!ATTLIST Surgery Duration CDATA #REQUIRED>

<!ELEMENT TraitExclude (#PCDATA)>
<!ATTLIST TraitExclude Trait CDATA #REQUIRED>

<!ELEMENT RemoveTrait (#PCDATA)>
<!ATTLIST RemoveTrait Trait CDATA #REQUIRED>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Treatments/AssJob.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment ShortName="AssJ">
    <Description>
        She will undergo surgery to "enhance" her ass.
        *(Takes 5 turns, less if a Nurse is on duty)
    </Description>

    <Surgery Duration="5">
        <TraitExclude Trait="Great Arse">${name} already has a Great Arse.</TraitExclude>
    </Surgery>

    <Messages>
        <Message Name="surgery">
            <Text>${name} is in the Clinic to get her ass worked on.</Text>
        </Message>
        <Message Name="doctor.work">
            <Text>Today, she worked on ${name}, sculpting her ass.</Text>
        </Message>

        <Include>DefaultSurgeryMessages.xml</Include>
    </Messages>
</Treatment>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Treatments/Fertility.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment ShortName="FrtT">
    <Description>
        She will undergo surgery to make her fertile.
        *(Takes up to 5 turns, less if a Nurse is on duty)
    </Description>

    <Surgery Duration="5">
        <TraitExclude Trait="Fertile">${name} is already as Fertile as she can be.</TraitExclude>
    </Surgery>

    <Messages>
        <Message Name="surgery">
            <Text>${name} is in the Clinic to get fertility treatment.</Text>
        </Message>

        <Message Name="doctor.work">
            <Text>Today, she worked on improving ${name}'s fertility.</Text>
        </Message>

        <Include>DefaultSurgeryMessages.xml</Include>
    </Messages>
</Treatment>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Treatments/CosmeticSurgery.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment ShortName="CosS">
    <Description>
        She will undergo magical surgery to "enhance" her appearance.
        *(Takes up to 5 turns, less if a Nurse is on duty)
    </Description>

    <Surgery Duration="5" />

    <Messages>
        <Message Name="surgery">
            <Text>${name} is in the Clinic to get cosmetic surgery.</Text>
        </Message>

        <Message Name="doctor.work">
            <Text>Today, she worked on improving ${name}'s appearance.</Text>
        </Message>

        <Include>DefaultSurgeryMessages.xml</Include>
    </Messages>
</Treatment>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Treatments/AngerManagement.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment ShortName="AMng">
    <Description>
        She will go to anger management to get over her anger problems. (Aggressive, Tsundere, Yandere)
    </Description>

    <Therapy Duration="4" FightChance="20" Title="therapy" SuccessBonus="3" HealthDanger="5">
        <RemoveTrait Trait="Aggressive">She is no longer Aggressive.</RemoveTrait>
        <RemoveTrait Trait="Tsundere">She is no longer a Tsundere.</RemoveTrait>
        <RemoveTrait Trait="Yandere">She is no longer a Yandere.</RemoveTrait>
    </Therapy>

    <Messages>
        <Message Name="therapy">
            <Text>${name} underwent therapy for anger issues.</Text>
        </Message>
        <Message Name="no-need">
            <Text>${name} doesn't need anger management.</Text>
        </Message>
        <Message Name="no-counselor">
            <Text>${name} has no counselor to help her with her anger issues.</Text>
        </Message>
        <Message Name="continue-therapy">
            <Text>She should stay in anger management to treat her other anger issues.</Text>
        </Message>
        <Message Name="death">
            <Text>She died in anger management.</Text>
        </Message>
        <Message Name="release">
            <Text>Her anger issues have been resolved, and she has been released from therapy.</Text>
        </Message>
    </Messages>
</Treatment>

=== DRSSX4756/crazys-wm-mod/Resources/Data/Treatments/BoobJob.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment ShortName="BbJb">
    <Description>
        She will undergo surgery to "enhance" her bust.
        *(Takes up to 3 turns per level, less if a Nurse is on duty)
    </Description>

    <Surgery Duration="3">
        <TraitExclude Trait="Titanic Tits">${name} already has Titanic Tits.</TraitExclude>
    </Surgery>

    <Messages>
        <Message Name="surgery">
            <Text>${name} is in the Clinic to get her breasts enlarged.</Text>
        </Message>

        <Message Name="doctor.work">
            <Text>Today, she enhanced ${name}'s boobs.</Text>
        </Message>

        <Include>DefaultSurgeryMessages.xml</Include>
    </Messages>
</Treatment>
